### ISSUE TITLE
darken the scene

### ISSUE THREAD

**Issue by swap-home** [SevernayaZemlya/GGJ_Echo_2017#2]
even after Window -> Lighting -> Ambient Light set to 0.01, the scene is still too bright.

May want to look at putting a black quad texture over the camera with a shader to adjust transparency

**Comment by matt-klassen** [comment]
I found a thread discussing a very similar issue [here.](https://forum.unity3d.com/threads/how-do-i-make-the-scene-completely-dark-black.51912/) Seems there are a few ways to go about it and none of them seem too complex.
